force-app/main/default/objects/consumer__c/consumer__c.object-meta.xml
<CustomObject>
    <label>consumer</label>
    <nameField>
        <label>consumer_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>consumer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/consumer__c/fields/consumer_Status__c.field-meta.xml
<CustomField>
    <fullName>consumer_Status__c</fullName>
    <label>consumer Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/consumer__c/fields/Phone_number__c.field-meta.xml
<CustomField>
    <fullName>Phone_number__c</fullName>
    <label>Phone number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Laptop_Bookings__c/Laptop_Bookings__c.object-meta.xml
<CustomObject>
    <label>Laptop Bookings</label>
    <nameField>
        <label>Laptop Bookings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Laptop Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Laptop_Bookings__c/fields/core_type__c.field-meta.xml
<CustomField>
    <fullName>core_type__c</fullName>
    <label>core type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Laptop_names__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>core i3</fullName>
            </value>
            <value>
                <fullName>core i5</fullName>
            </value>
            <value>
                <fullName>core i7</fullName>
            </value>
            <value>
                <fullName>Bionic chip .</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Laptop_Bookings__c/fields/How_Many_Months__c.field-meta.xml
<CustomField>
    <fullName>How_Many_Months__c</fullName>
    <label>How Many Months</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Laptop_Bookings__c/fields/Laptop_names__c.field-meta.xml
<CustomField>
    <fullName>Laptop_names__c</fullName>
    <label>Laptop names</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>Acer</fullName>
            </value>
            <value>
                <fullName>Hp</fullName>
            </value>
            <value>
                <fullName>Mac</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Laptop_Bookings__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <referenceTo>consumer__c</referenceTo>
    <relationshipLabel>Laptop Bookings</relationshipLabel>
    <relationshipName>Laptop_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Laptop_Bookings__c/fields/Total_No_Of_Laptops__c.field-meta.xml
<CustomField>
    <fullName>Total_No_Of_Laptops__c</fullName>
    <label>Total No Of Laptops</label>
    <referenceTo>Total_Laptops__c</referenceTo>
    <relationshipLabel>Laptop Bookings</relationshipLabel>
    <relationshipName>Laptop_Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Total_Laptops__c/Total_Laptops__c.object-meta.xml
<CustomObject>
    <label>Total Laptops</label>
    <nameField>
        <label>Total Laptops</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Total Laptops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LaptopBookingHandlerTest.cls
@isTest
private class LaptopBookingHandlerTest {
    @isTest
    static void testSendEmailNotification() {
        consumer__c consumer = new consumer__c(
            Name = 'John Doe',
            Phone_number__c = '9887346134',
            Address__c = 'Paris, France',
            Email__c = 'johndoe@example.com',
            consumer_Status__c = 'Student'
        );
        insert consumer;
        System.debug('Consumer Id: ' + consumer.Id);
        Total_Laptops__c totalLaptops = new Total_Laptops__c(
            Name = '1'
        );
        insert totalLaptops;
        List<Laptop_Bookings__c> lapBookings = new List<Laptop_Bookings__c>();
        lapBookings.add(new Laptop_Bookings__c(
            Name = 'Booking11',
            Email__c = consumer.Email__c,
            Name__c = consumer.Id,
            Amount__c = 900,
            core_type__c = 'core i3',
            Laptop_names__c = 'Dell',
            Total_No_Of_Laptops__c = totalLaptops.Id,
            How_Many_Months__c = '1'
        ));
        insert lapBookings;
        Test.startTest();
        LaptopBookingHandler.sendEmailNotification(lapBookings);
        Test.stopTest();
        Integer sentEmailCount = Limits.getEmailInvocations();
        System.assertEquals(2, sentEmailCount, 'Two emails should have been sent.');
    }
}